### ISSUE TITLE
OpenAPI has a couple of broken links to images in the README.md

### ISSUE THREAD

**Issue by ReallyMetro** [hackolade/OpenAPI#37]
I noticed a couple of malfunctioning png images in the ReadMe. 
One is just missing and the other has some technical problem.

This just 404s @ line 155 (I think):
https://github.com/hackolade/OpenAPI/raw/master/lib/Swagger%20-%20Add%20request%20action%20menu.png

This doesn't work @ line 175 for some reason that is beyond my meagre understanding.:
![](lib/OpenAPI - Responses.png) 

Thanks. I'll check back in a few days.

**Comment by pdesmarets** [comment]
Good catch!  Thank you.  It is fixed now.
You may want to take a look also at our tutorial https://hackolade.com/help/Addreusabledefinitions.html
