### ISSUE TITLE
Swagger/Open API Path extensions (i.e., 'x-') not being generated during forward engineering.

### ISSUE THREAD

**Issue by CodeGenX** [hackolade/OpenAPI#6]
Attached is a Hackolda file with extension tests for forward engineering tests. Another test is to add path/operation extensions to an existing OpenAPI file and reverse engineer then forward engineer to a different file for comparison.

Hackoldade properly reverse engineers all swagger/OpenAPI structure extensions.
However, the path and many of its subset structure extensions are not forward engineered. I tried numerous test variations with no luck. Hoping it's due to a new user error, please advise.

Looked at the following file to see if path extensions were being handled during forward engineering:  
/forward_engineering/helpers/pathHelper.js 
'const extensions = getExtensions(data.operationExtensions);'

Thanks in advance.
[api-with-path-extensions.zip](https://github.com/hackolade/OpenAPI/files/4527137/api-with-path-extensions.zip)

**Comment by pdesmarets** [comment]
Thanks for the heads up.  We did find an issue with schema extensions handling.  We've just released a new version of both plugins.  Let me know if this is more like what you expected.

**Comment by CodeGenX** [comment]
Much appreciated for the ultra prompt response! 

Path and Response extensions 'x-' are now working using OpenAPI (0.1.17) and Swagger (0.1.23). It now will forward engineer the 'x-' extension when the 'patten' has an associated 'value'.

I'll close this issue.

However, I'll test OpenAPI components again since I'm not seeing the 'requestBodies->requestBody' being generated and may be a different issue.

See the attached test.

Thanks again!
[api-with-examples - OpenAPI Schema test.zip]
(https://github.com/hackolade/OpenAPI/files/4530892/api-with-examples.-.OpenAPI.Schema.test.zip)

**Comment by pdesmarets** [comment]
Thanks.  If you find anything else we can improve, don't hesitate to contact us here or by opening a ticket at support@hackolade.com
